<a href="https://colab.research.google.com/github/Tanmay2262/Machine-Learning/blob/main/Aritficial_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing libraries

In [51]:
%tensorflow_version 2.x

In [52]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [53]:
tf.__version__

'2.5.0'

# Data Preprocessing



> Importing Dataset


In [54]:
df = pd.read_csv('/content/drive/MyDrive/ML Tasks/Machine Learning A-Z (Codes and Datasets)/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Python/Churn_Modelling.csv')
x = df.iloc[: , 3:-1].values
y = df.iloc[:, -1].values

In [55]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [56]:
y

array([1, 0, 1, ..., 1, 1, 0])



> Encoding Categorical Data



In [57]:
# Encoding Gender Column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [58]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [59]:
#  one Hot Encoding Geography Column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers= [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [60]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]




>  Splitting into Training set and test set




In [61]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)



> Feature Scaling



In [62]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [63]:
print(x_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


# Building the ANN



> Initialising the ANN 



In [64]:
ann = tf.keras.models.Sequential()



> Adding the input layer and the first hidden layer



In [65]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))



> Adding the second hidden layer 



In [66]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))



> Adding the Output Layer



In [67]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
# for non-binary Classification we use the activation = 'softmax'

# Training the ANN



> Compiling the ANN



In [68]:
ann.compile(optimizer='adam', loss='binary_crossentropy' ,metrics= ['accuracy'])
# for binary clasification the loss = 'binary_crossentropy' and for non- binary classifications we use loss = 'categorical_crossentropy'



> Training the ANN on the Training Set



In [69]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.8092 - accuracy: 0.5434
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5599 - accuracy: 0.7849
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4886 - accuracy: 0.8081
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4544 - accuracy: 0.8142
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4380 - accuracy: 0.8171
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4254 - accuracy: 0.8219
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4132 - accuracy: 0.8275
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4021 - accuracy: 0.8326
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3900 - accuracy: 0.8391
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3794 - accura

# Making the predictions and evaluating the model

In [70]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]




> Predicting the test set result



In [71]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]




> Confusion Matrix



In [72]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1522   73]
 [ 206  199]]


0.8605